### ISSUE TITLE
Sintesis

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-JudithReynaCS#1]
[SINTESIS_JUDITHREYNACRUZSANTIAGO_7US.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-JudithReynaCS/files/12704049/SINTESIS_JUDITHREYNACRUZSANTIAGO_7US.pdf)

**Comment by ang3-l32** [comment]
calificación:18 
 falta bibliografía

**Comment by Aricel117** [comment]
Calificación: 18
faltan bibliografías consultadas

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
